# Flow: stages -> stage -> jobs -> job -> steps -> task1, task2, task3

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  #'$(Build.SourceVersion)' 
  #

pool: 'TestAgentsPool'

stages:
  - stage: Build
    displayName: Build Job
    jobs: 
     - job: Build
       displayName: Build Job
       pool: 'TestAgentPool' 
       steps:
         
       - task: Docker@2
         inputs:
           containerRegistry: 'devops-app-deployments-to-acr-svc'
           repository: 'devopsaks01'
           command: 'buildAndPush'
           Dockerfile: '**/Dockerfile'
           tags: '$(Build.BuildId)'
  
       - task: CopyFiles@2
         inputs:
           SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
           Contents: '**'
           TargetFolder: '$(Build.ArtifactStagingDirectory)'
           OverWrite: true

       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'kube-manifests'
           publishLocation: 'Container'