apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4-acr01-deployment
  labels:
    app: app4-acr01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app4-acr01
  template:
    metadata:
      labels:
        app: app4-acr01
    spec:
        containers:
          - name: acrdemo-localdocker
            image: acr01sade.azurecr.io/app4/app4ngnixaks
            imagePullPolicy: Always
            ports:
              - containerPort: 80
        # imagePullSecrets: # update secret name created 
        #   - name: acrsade-secret 

---


apiVersion: v1
kind: Service
metadata:
  name: app4-acr01-service
  labels:
    app: app4-acr01
spec:
  type: LoadBalancer
  selector:
    app: app4-acr01
  ports:
    - port: 80
      targetPort: 80
