############################
## Deployment file ##
############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment01-aks-app1
  labels:
    app: devop-app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devop-app01
  template:
    metadata:
      labels:
        app: devop-app01
    spec:
        containers:
          - name: acrdemo-aks-docker
            image: acr01sade.azurecr.io/devopsaks01:v1
            imagePullPolicy: Always
            ports:
              - containerPort: 80
        # imagePullSecrets: # update secret name created 
        #   - name: acrsade-secret 

---


apiVersion: v1
kind: Service
metadata:
  name: devops-aks-service
  labels:
    app: devopsaks01
spec:
  type: LoadBalancer
  selector:
    app: devopsaks01
  ports:
    - port: 80
      targetPort: 80
