apiVersion: apps/v1
kind: Deployment
metadata:
  name: app5-aks-deployment
  labels:
    app: app5-aks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app5-aks
  template:
    metadata:
      labels:
        app: app5-acr01
    spec:
        containers:
          - name: acrdemo-aks-docker
            image: acr01sade.azurecr.io/aks/app5ngnixaks
            imagePullPolicy: Always
            ports:
              - containerPort: 80
        # imagePullSecrets: # update secret name created 
        #   - name: acrsade-secret 

---


apiVersion: v1
kind: Service
metadata:
  name: app5-aks-service
  labels:
    app: app5-aks
spec:
  type: LoadBalancer
  selector:
    app: app5-aks
  ports:
    - port: 80
      targetPort: 80
